language: php
php:
  - '7.1'
before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration ./phpunit.xml.dist